spring:
  resources:
    static-locations: file:${work.home}/static/
  datasource:
    url: jdbc:h2:file:${work.home}/dbdata/h2/orderlunch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

logging:
  file: ${work.home}/logs/order-lunch.log

order:
  lunch:
    web:
      member-define-file: ${work.home}/conf/members.json