spring:
  resources:
    static-locations: file:${work.home}/static/

logging:
  file: ${work.home}/logs/order-lunch.log

order:
  lunch:
    web:
      member-define-file: ${work.home}/conf/members.json