server:
  port: 9080
  servlet:
    context-path: /
    application-display-name: Order Lunch App
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

logging:
  path: ${user.dir}/logs

spring:
  resources:
    static-locations: classpath:/static/

unorder:
  member:
    notifyTime: 0 35 10 ? * MON-FRI

wehook: https://oapi.dingtalk.com/robot/send?access_token=344b102369e87573404797a1cd97ba06cfa01e06c8f61ee2b54bb2a44ef27802