spring:
  resources:
    static-locations: classpath:/static/

logging:
  file: ${user.dir}/logs/order-lunch.log

order:
  lunch:
    web:
      member-define-file: ${user.dir}/src/main/resources/members.json