server:
  port: 9080
  servlet:
    context-path: /
    application-display-name: Order Lunch App
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  datasource:
    platform: h2
    username: root
    password: Root_123
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

unorder:
  member:
    notify-switch-on: false
    notifyTime: 0 35 10 ? * MON-FRI
    wehook: https://oapi.dingtalk.com/robot/send?access_token=344b102369e87573404797a1cd97ba06cfa01e06c8f61ee2b54bb2a44ef27802
order:
  cache:
    clean:
      switch-on: true
      cron: 0 0 0 * * *

